### ISSUE TITLE
JavaScript-like anonymous function

### ISSUE THREAD

**Issue by denismaciel** [egnha/nofrills#16]
Hey Eugene, I was wondering (out of sheer curiosity) if it is possible to implement Javascript's syntax for anonymous function in R and stumbled upon your package. It seems to be very cool!

Do you think it is viable to implement something like this in R?

```
(x, y) => {
    x + y
}
```

**Comment by egnha** [comment]
Hi Denis, it would certainly be nice if that were possible. Unfortunately, it's not, short of changing the R interpreter itself, because `(x, y)` is a syntactically invalid expression. (Try `quote((x, y))`.)

Nitpicking aside, it's possible to cook up something syntactically close. Here's the first possibility that comes to mind:

```R
`%=>%` <- function(args, body, sym = as.name(".")) {
  args <- parse_args(substitute(args), sym)
  body <- substitute(body)
  fn(!!! args, ~ !! body)
}

parse_args <- function(args, sym) {
  if (args %called_with% sym)
    args[[1]] <- rlang::exprs
  eval(args, parent.frame(2))
}

`%called_with%` <- function(x, sym) {
  is.call(x) && identical(x[[1]], sym)
}
```
It works like this:

```R
.(x, y) %=>% { x + y }
#> function (x, y) 
#> {
#>   x + y
#> }

# Supports quasiquotation
one <- 1
two <- 2
.(x, y = !! one) %=>% { x + y + !! two }
#> function (x, y = 1) 
#> {
#>   x + y + 2
#> }

# Alternatively, you can prefabricate arguments and feed them in
args <- alist(x, y = 1, ... = )
args %=>% { x + y }
#> function (x, y = 1, ...) 
#> {
#>   x + y
#> }
```

However, the disadvantages of this operator syntax over `fn()` are:

- it's more verbose, yet not more capable
- `%=>%` is already taken in the [dub](https://github.com/egnha/dub) package ;)

**Comment by denismaciel** [comment]
Thanks for taking the time to answer! It's already in my todo list to *study* this package. 

Hope you have a new trick to show us in the next Berlin R Users Group's Meetup. :)
